var langs = {
    'en-US': {
        '*requiredFields': '* required fields',
        '1.assignARole': '1. Assign a role',
        '1.selectAnOrg': '1. Select an org',
        '2.assignAnOrg': '2. Assign an org (star (*) represents all orgs)',
        '2.selectASpace': '2. Select a space',
        '3.assignSpaces': '3. Assign spaces (star (*) represents all space of assigned org)',
        '3.selectASrp': '3. Select a SRP',
        '4.selectScopes': '4. Select scopes',
        'accessIsDenied': 'Access is denied.',
        'accounts': 'Accounts',
        'action*': 'Action*',
        'activate': 'Activate',
        'activateCheckingMessage': 'Please check 1 or more users.',
        'activateQuotaCheckingMessage': 'If you want to activate reviewing user with quota plan, please check exactly 1 user.',
        'activateReviewingUsersTitle': 'Activate Reviewing Users',
        'activateReviewingUserWithPlanTitle': 'Activate Reviewing User with Plan',
        'activateSuccessfully': 'Activate successfully.',
        'activationCode': 'Activation code',
        'activationCode*': 'Activation code*',
        'add': 'Add',
        'address': 'Address',
        'addSuccessfully': 'Add successfully.',
        'adminOnlyMessage': 'Admin cannot exist at the same time as other roles.',
        'advancedUserProfile': 'Advanced user profile',
        'all': 'All',
        'alternativeEmail': 'Alternative Email',
        'append': 'Append',
        'appId*': 'App ID*',
        'appInstanceLimit': 'App instances limit',
        'assignQuota': 'Assign Quota',
        'assignRoleAndOrgMessage': 'Please assign at least one role and one org to an user.',
        'assignSpaceMessage': 'Please assign at least one space to an user.',
        'assignSpaceToDeveloperMessage': 'Please assign at least one space when the number of developers is not equal to zero.',
        'atLeast1Digit': 'at least 1 digit',
        'atLeast1LowerCaseLetter': 'at least 1 lower case letter',
        'atLeast1SpecialCharacter': 'at least 1 special character',
        'atLeast1UpperCaseLetter': 'at least 1 upper case letter',
        'atLeast8Characters': 'at least 8 characters',
        'attention': 'Attention',
        'authenticationTest': 'Authentication test',
        'baseDns': 'Base distinguished name(s)',
        'baseDnsSplitingPolicyHint': 'Use semicolon to separate the base distinguished names, ex: ou=x,dc=com;ou=y,dc=com.',
        'baseUsername*': 'Base username*',
        'basicUserProfile': 'Basic user profile',
        'bindDn': 'Bind distinguished name',
        'cancel': 'Cancel',
        'cfScopes': 'CF scopes',
        'change': 'Change',
        'changePasswordSuccessfully': 'Change password successfully. Please sign in again.',
        'changePasswordTitle': 'Change Password',
        'chooseAPlanForCurrentUser*': 'Choose a plan for current user*',
        'city': 'City',
        'clear': 'Clear',
        'close': 'Close',
        'completeRegistrationTitle': 'Complete Registration',
        'company': 'Company',
        'company*': 'Company*',
        'contactPhone': 'Contact phone',
        'continue': 'Continue',
        'country': 'Country / Region',
        'create': 'Create',
        'createMarketplaceTitle': 'Create Marketplace',
        'createOrgLink': 'Create a new org',
        'createSrpTitle': 'Create SRP',
        'createSuccessfully': 'Create successfully.',
        'createTrainingUsersTitle': 'Create Training Users',
        'createUserTitle': 'Create User',
        'creationTime': 'Creation time',
        'creator': 'Creator',
        'currentUser': 'Current user',
        'configLdapContent': '<strong>How to test:</strong><p>Please enter the LDAP user\'s username and password and click the Test button.</p>',
        'confirm': 'Confirm',
        'connect': 'Connect',
        'data-error': 'Please enter correct format.',
        'data-error-email': 'Please enter the correct Email format.',
        'data-error-url': 'Please enter the correct URL format.',
        'data-match-error': 'The new password entered twice is inconsistent.',
        'data-minlength-error': 'Not long enough.',
        'data-pattern-error': 'Please match the requested format.',
        'data-pattern-error-basic': 'Please enter the requested format. (cannot use greater than (>) and less then (<))',
        'data-required-error': 'Please fill out this field.',
        'deactivate': 'Deactivate',
        'deactivateSuccessfully': 'Deactivate successfully.',
        'delete': 'Delete',
        'deleteMarketplaceMessage': 'Are you sure to delete marketplace?',
        'deleteSrpMessage': 'Are you sure to delete SRP?',
        'deleteSuccessfully': 'Delete successfully.',
        'deleteTrainingUsersMessage': 'Are you sure to delete these training users?',
        'description': 'Description',
        'didn\'tReceiveTheRegistrationEmail?': 'Didn\'t receive the registration Email?',
        'disable': 'Disable',
        'disableSuccessfully': 'Disable successfully.',
        'disableUserMessage': 'Are you sure to disable user?',
        'disconnect': 'Disconnect',
        'don\'tHaveAccount?': 'Don\'t have account?',
        'e.g.': 'e.g., ',
        'edit': 'Edit',
        'editUserScopesTitle': 'Edit User Scopes',
        'emptyActivationCodeMessage': 'The \'authorization code\' field cannot be empty.',
        'emptyNewPwdConfirmationMessage': 'The \'new password confirmation\' field cannot be empty.',
        'emptyNewPwdMessage': 'The \'new password\' field cannot be empty.',
        'emptyPwdMessage': 'The \'password\' field cannot be empty.',
        'emptyResult': 'Empty Result.',
        'emptyUsernameMessage': 'The \'username\' field cannot be empty.',
        'enable': 'Enable',
        'enabled': 'Enabled',
        'enableSuccessfully': 'Enable successfully.',
        'enableUserMessage': 'Are you sure to enable user?',
        'enterManually': 'Enter manually',
        'exceptSpaceBackslashAndDoubleQuotes': 'except space ( ), backslash (\\) and double quotes (")',
        'failedUsers': 'Failed users',
        'fieldName': 'Field name',
        'fieldValue': 'Field value',
        'firstName': 'First name',
        'firstName*': 'First name*',
        'firstTimeSignedInMessage': 'For the first login, we recommend that you change the default password immediately.',
        'firstTimeSignedInForcedMessage': 'For the first login, please change the default password immediately.',
        'forgetPassword?': 'Forget password?',
        'fuzzySearch': 'Fuzzy search',
        'generateAutomatically': 'Generate automatically',
        'go': 'Go',
        'goToChangePassword': 'Go to change password',
        'help': 'Help',
        'highestRole': 'Highest role (current org role)',
        'host': 'Host',
        'incorrectNewPwdConfirmationMessage': 'The \'new password confirmation\' is incorrect.',
        'industry': 'Industry',
        'instanceMemory': 'App instance available memory',
        'insufficientPermissionsToReviveMessage': 'You do not have sufficient permissions to revive this user.',
        'invalidUsernameMessage': 'The \'username\' format is invalid.',
        'invalidNewPwdMessage': 'The \'new password\' does not meet the password policy.',
        'invite': 'Invite',
        'inviteSuccessfully': 'Invite successfully',
        'inviteUserMessage': 'User already exists. Would you like to invite this user to your org?',
        'lang': 'Language',
        'large': 'Large',
        'lastModifiedTime': 'Last modified time',
        'lastName': 'Last name',
        'lastName*': 'Last name*',
        'ldap': 'LDAP',
        'ldapConnectSuccessfully': 'Successfully connected to the LDAP server.',
        'ldapDisconnectSuccessfully': 'Successfully disconnected to the LDAP server.',
        'ldapSettings': 'LDAP settings',
        'ldapTestPassed': 'Test passed.',
        'ldapUsername': 'LDAP username',
        'ldapUsername*': 'LDAP username*',
        'listProcessingUsersTitle': 'List Processing Users',
        'loadingOrgs...': 'Loading orgs...',
        'loadingSpaces...': 'Loading spaces...',
        'manage': 'Manage',
        'manageFailedUsersTitle': 'Manage Failed Users',
        'manageMarketplacesTitle': 'Manage Marketplaces',
        'manageMarketplaceTitle': 'Manage Marketplace',
        'managementPortalIntro': 'Organization, user and service management',
        'managementPortalTitle': 'Management Portal',
        'manageReviewersTitle': 'Manage Reviewers',
        'manageSrpsHint': 'Please select an org to list.',
        'manageSrpsTitle': 'Manage SRPs',
        'manageSrpTitle': 'Manage SRP',
        'manageTrainingUsersTitle': 'Manage Training Users',
        'manageUsersHint': 'Please select an org or a role to list.',
        'manageUsersTitle': 'Manage Users',
        'manageUserTitle': 'Manage User',
        'mappingToGuidOfSrp': 'Mapping to GUID of SRP (App) on Cloud Foundry',
        'mappingToOrg': 'Mapping to Org of Cloud Foundry',
        'mappingToSpace': 'Mapping to Space of Cloud Foundry',
        'marketplaceId': 'Marketplace ID',
        'marketplaceId*': 'Marketplace ID*',
        'marketplaceNameIsAlreadyInUse': 'Marketplace name is already in use.',
        'marketplaces': 'Marketplaces',
        'marketplace': 'Marketplace',
        'medium': 'Medium',
        'moreInfo': 'More info',
        'mpFailMessage': 'The token provided is invalid.',
        'myProfileTitle': 'My Profile',
        'mySrps': 'My SRPs',
        'name': 'Name',
        'name*': 'Name*',
        'namingPolicyHint': 'Allowed symbols: Underscore (_) and dash (-).',
        'newOrgHint': 'The new org will be created with the user.',
        'newOrgName': 'New org name',
        'newPassword': 'New password',
        'newPassword*': 'New password*',
        'newPasswordConfirmation*': 'New password confirmation*',
        'newPasswordConfirmationHint': 'Please enter new password again.',
        'noFailedUser': 'No failed user.',
        'noExamplePhone': 'No example phone',
        'noProcessingUser': 'No processing user.',
        'noReviewer': 'No reviewer.',
        'noReviewingUser': 'No reviewing user.',
        'noScopeCanBeAppended': 'User has all scopes of this SRP.',
        'noScopeCanBeRemoved': 'User does not have any scopes of this SRP.',
        'noSpaceMessage': 'No space existing, please choose another org.',
        'noSrpMessage': 'No SRP existing, please choose another space.',
        'notificationUrl': 'notification URL',
        'notificationUrl*': 'notification URL*',
        'numOfDevelopers': 'Number of developers',
        'numOfTenants': 'Number of tenants',
        'officePhone': 'Office phone',
        'operations': 'Operations',
        'org': 'Org',
        'org*': 'Org*',
        'orgId*': 'Org ID*',
        'orgNameAlreadyExists': 'Org name already exists.',
        'orgNamingPolicyHint': 'Only Allowed symbol: Dash (-).',
        'origin': 'Origin',
        'oneRoleOneOrgMessage': 'An user can only be assigned to one role in an organization.',
        'paasPermissionsSetting': 'PaaS permissions setting',
        'paasPermissionSettingList*': 'PaaS permission setting list*',
        'pageIsRedirecting...': 'Page is redirecting...',
        'partOfMarketplaceName': 'Part of marketplace name',
        'partOfSrpName': 'Part of SRP name',
        'partOfUsername': 'Part of username',
        'password': 'Password',
        'password*': 'Password*',
        'passwordExpiresMessage': 'You have not changed your password for a long time, we recommend that you change your password immediately.',
        'passwordExpiresForcedMessage': 'You have not changed your password for a long time, please change your password immediately.',
        'passwordOperationTitle': 'Password Operation',
        'passwordPolicy': 'Password policy',
        'phoneIsInvalid': 'Phone number for this region is invalid.',
        'port': 'Port',
        'postalCode': 'Postal code',
        'processingStatus': 'Processing status',
        'processingUsers': 'Processing users',
        'reasonForFailure': 'Reason for failure',
        'redirectingMessage': 'Page will be redirecting after 5 seconds.',
        'refreshingMessage': 'Page will be refreshing after 5 seconds.',
        'regionCode': 'Region code',
        'regionCodeIsInvalid': 'Please select region code.',
        'rememberMe': 'Remember me',
        'remindMeNextTime': 'Remind me next time',
        'remove': 'Remove',
        'removeReviewerMessage': 'Are you sure to remove user \'$username\' from reviewer list?',
        'removeSuccessfully': 'Remove successfully.',
        'resendRegEmail': 'Resend registration Email',
        'resendRegEmailContent1': 'If you don\'t receive registration Email after complete registration you can use this tool to resend it. Upon submission you will receive an Email with the link to complete the process.',
        'resendRegEmailContent2': 'To resend registration Email, enter your username (Email), then click \'Submit\'.',
        'resendRegEmailSuccessfully': 'Resend registration Email successfully.',
        'resendRegEmailTitle': 'Enter Email to resend registration Email',
        'reset': 'Reset',
        'resetPassword': 'Reset password',
        'resetPasswordContent': 'You have to change the password with activation code and meets the password policy. The password policy is:',
        'resetPasswordSuccessfully': 'Reset password successfully.',
        'resetSuccessfully': 'Reset successfully.',
        'resetTrainingUsersMessage': 'Are you sure to reset these training users?',
        'returnToLogin': 'Return to login',
        'reviewers': 'Reviewers',
        'reviewingUsers': 'Reviewing users',
        'revive': 'Revive',
        'reviveCheckingMessage': 'Please select an user.',
        'reviveFailedUserTitle': 'Revive Failed User',
        'reviveSuccessfully': 'Revive successfully.',
        'role': 'Role',
        'role*': 'Role*',
        'ownedScopes': 'Owned scopes',
        'save': 'Save',
        'scopes': 'Scopes',
        'scopes*': 'Scopes*',
        'selectNumberOfTenantsOrDevelopersMessage': 'Please select the number of tenant or developer.',
        'sendPwdResetEmail': 'Send password reset Email',
        'sendPwdResetEmailContent1': 'If you can\'t remember your password you can use this tool to reset it. Upon submission you will receive an Email with the link to complete the process.',
        'sendPwdResetEmailContent2': 'To send password reset Email, enter your username (Email), then click \'Submit\'.',
        'sendPwdResetEmailSuccessfully': 'Send password reset Email successfully.',
        'sendPwdResetEmailTitle': 'Enter Email to send password reset Email',
        'show': 'Show',
        'skip': 'Skip',
        'small': 'Small',
        'signIn': 'Sign in',
        'signInAgain': ' Please sign in again.',
        'signInFirst': ' Please sign in first.',
        'signingInWithThirdParty...': 'Signing in with third-party...',
        'signInTitle': 'Sign in to Developer Network',
        'signInWithThird-party': 'Sign in with third-party',
        'signOut': 'Sign out',
        'signUp': 'Sign up',
        'signUpSuccessfully': 'Sign up successful. We will review your account. You will receive an registration Email after the reviewing process is passed.',
        'signUpTitle': 'Sign Up',
        'space': 'Space',
        'space*': 'Space*',
        'spaceId*': 'Space ID*',
        'spaces': 'Spaces',
        'spaces*': 'Spaces*',
        'splitingPolicyHint': 'Use commas to separate the scopes, ex: read, write, etc.',
        'srp': 'SRP',
        'srp*': 'SRP*',
        'srpNameIsAlreadyInUse': 'SRP name in specified org and space is already in use.',
        'srpId': 'SRP ID',
        'srpId*': 'SRP ID*',
        'srps': 'SRPs',
        'standard': 'Standard',
        'status': 'Status',
        'submit': 'Submit',
        'supportPortalIntro': 'Online support and discussion',
        'supportPortalTitle': 'Support Portal',
        'sure': 'Sure',
        'systemNotification': 'System notification',
        'technicalPortalIntro': 'Platform Related Technical documents',
        'technicalPortalTitle': 'Technical Portal',
        'tel': 'Tel',
        'tenantOnlyMessage': 'The page operations depend on your permissions in org.',
        'test': 'Test',
        'thePasswordPolicy:': 'The password policy:',
        'ticketerOnlyMessage': 'Ticketer cannot exist at the same time as other roles.',
        'totalMemory': 'Total avaliable memory',
        'totalRoute': 'Total avaliable routes',
        'totalService': 'Total available services',
        'trainingUserList': 'Training user list',
        'trainingUsers': 'Training users',
        'trainingUsersTitle': 'Training Users',
        'uid': 'Unique identifier (uid)',
        'unlimited': 'Unlimited',
        'unlock': 'Unlock',
        'unlockYourAccount': 'Unlock your account',
        'unlockYourAccountContent': 'You have to change the default password and meets the password policy when you sign in for the first time. The password policy is:',
        'unlockSuccessfully': 'Unlock successfully. Please sign in again.',
        'updateSuccessfully': 'Update successfully.',
        'useOrgsLink': 'Use existing orgs',
        'userId': 'User ID',
        'userIsAlreadyAReviewer': 'User is already a reviewer.',
        'username': 'Username (Email)',
        'username*': 'Username (Email)*',
        'usernameIsAlreadyInUse': 'Username is already in use.',
        'user': 'User',
        'userAlreadyExistsInOrg': 'User already exists in your org, please use the Manage User feature to update.',
        'users': 'Users',
        'validPeriod*': 'Valid period (days) *',
        'youDoNotHaveAnyOrg': 'You do not have any org.',
        'youDoNotHaveAnySrp': 'You do not have any SRP.'
    },
    'zh-TW': {
        '*requiredFields': '* 必要欄位',
        '1.assignARole': '1. 指派角色',
        '1.selectAnOrg': '1. 選擇組織',
        '2.assignAnOrg': '2. 指派組織（星號（*）代表所有組織）',
        '2.selectASpace': '2. 選擇空間',
        '3.assignSpaces': '3. 指派空間（星號（*）代表指派組織的所有空間）',
        '3.selectASrp': '3. 選擇 SRP',
        '4.selectScopes': '4. 選擇權限',
        'accessIsDenied': '存取被拒。',
        'accounts': '帳戶',
        'action*': '操作*',
        'activate': '啟用',
        'activateCheckingMessage': '請勾選1或多位使用者。',
        'activateQuotaCheckingMessage': '如果要使用配額計畫啟用審核中的使用者，請確認僅勾選1位使用者。',
        'activateReviewingUsersTitle': '啟用所有審核中的使用者',
        'activateReviewingUserWithPlanTitle': '依計畫啟用審核中的使用者',
        'activateSuccessfully': '啟用成功。',
        'activationCode': '啟用碼',
        'activationCode*': '啟用碼*',
        'add': '添加',
        'address': '地址',
        'addSuccessfully': '添加成功。',
        'adminOnlyMessage': '管理員不能與其他角色同時存在。',
        'advancedUserProfile': '進階使用者資料',
        'all': '全部',
        'alternativeEmail': '備用電子郵件',
        'append': '追加',
        'appId*': 'App ID*',
        'appInstanceLimit': '應用實體總數上限',
        'assignQuota': '指派額度',
        'assignRoleAndOrgMessage': '請至少指派一個角色和一個組織給使用者。',
        'assignSpaceMessage': '請至少指派一個空間給使用者。',
        'assignSpaceToDeveloperMessage': '當 developer 的數量不等於零時, 請至少指派一個空間。',
        'atLeast1Digit': '至少1個數字',
        'atLeast1LowerCaseLetter': '至少1個小寫字母',
        'atLeast1SpecialCharacter': '至少1個特殊字元',
        'atLeast1UpperCaseLetter': '至少1個大寫字母',
        'atLeast8Characters': '至少8個字元',
        'attention': '注意',
        'authenticationTest': '認證測試',
        'baseDns': '基礎可分辨名稱',
        'baseDnsSplitingPolicyHint': '使用分號分隔基礎可分辨名稱，例如：ou=x,dc=com;ou=y,dc=com。',
        'baseUsername*': '基礎使用者名稱*',
        'basicUserProfile': '基本使用者資料',
        'bindDn': '綁定可分辨名稱',
        'cancel': '取消',
        'cfScopes': 'CF 權限',
        'change': '更改',
        'changePasswordSuccessfully': '密碼更改成功。請重新登入。',
        'changePasswordTitle': '更改密碼',
        'chooseAPlanForCurrentUser*': '為當前使用者選擇一個計畫*',
        'city': '城市',
        'clear': '清除',
        'close': '關閉',
        'completeRegistrationTitle': '完整註冊',
        'company': '公司',
        'company*': '公司*',
        'contactPhone': '聯絡電話',
        'continue': '繼續',
        'country': '國家 / 地區',
        'create': '創建',
        'createMarketplaceTitle': '創建新的市集',
        'createOrgLink': '創建新的組織',
        'createSrpTitle': '創建新的SRP',
        'createSuccessfully': '創建成功。',
        'createTrainingUsersTitle': '創建培訓用的使用者',
        'createUserTitle': '創建使用者',
        'creationTime': '創建時間',
        'creator': '創建者',
        'currentUser': '當前使用者',
        'configLdapContent': '<strong>如何測試：</strong><p>請輸入 LDAP 使用者的使用者名稱和密碼, 然後按一下 "測試" 按鈕。</p>',
        'confirm': '確認',
        'connect': '連接',
        'data-error': '請輸入正確的格式。',
        'data-error-email': '請輸入正確的電子郵件格式。',
        'data-error-url': '請輸入正確的 URL 格式。',
        'data-match-error': '輸入兩次的新密碼不一致。',
        'data-minlength-error': '長度不足。',
        'data-pattern-error': '請符合所需格式。',
        'data-pattern-error-basic': '請符合所需格式。（不能使用大於（>）和小於（<））',
        'data-required-error': '請填寫這個欄位。',
        'deactivate': '取消啟用',
        'deactivateSuccessfully': '取消啟用成功。',
        'delete': '刪除',
        'deleteMarketplaceMessage': '是否確定要刪除市集？',
        'deleteSrpMessage': '是否確定要刪除 SRP？',
        'deleteSuccessfully': '刪除成功。',
        'deleteTrainingUsersMessage': '是否確定要刪除這些培訓用的使用者？',
        'description': '描述',
        'didn\'tReceiveTheRegistrationEmail?': '沒有收到註冊電子郵件？',
        'disable': '停用',
        'disableSuccessfully': '停用成功。',
        'disableUserMessage': '是否確定要停用使用者？',
        'disconnect': '斷開連接',
        'don\'tHaveAccount?': '沒有帳戶？',
        'e.g.': '例如：',
        'edit': '編輯',
        'editUserScopesTitle': '編輯使用者權限',
        'emptyActivationCodeMessage': '"授權代碼" 欄位不能為空。',
        'emptyNewPwdConfirmationMessage': '"新密碼確認" 欄位不能為空。',
        'emptyNewPwdMessage': '"新密碼" 欄位不能為空。',
        'emptyPwdMessage': '"密碼" 欄位不能為空。',
        'emptyResult': '沒有結果。',
        'emptyUsernameMessage': '"使用者名稱" 欄位不能為空。',
        'enable': '啟用',
        'enabled': '啟用',
        'enableSuccessfully': '啟用成功。',
        'enableUserMessage': '是否確定要啟用使用者？',
        'enterManually': '手動輸入',
        'exceptSpaceBackslashAndDoubleQuotes': '禁止空格（ ）、反斜線（\\）、雙引號（"）字元',
        'failedUsers': '失敗的使用者',
        'fieldName': '欄位名稱',
        'fieldValue': '欄位值',
        'firstName': '名字',
        'firstName*': '名字*',
        'firstTimeSignedInMessage': '您為首次登入，我們建議您立即更改預設密碼。',
        'firstTimeSignedInForcedMessage': '您為首次登入，請立即更改預設密碼。',
        'forgetPassword?': '忘記密碼？',
        'fuzzySearch': '模糊搜尋',
        'generateAutomatically': '自動產生',
        'go': '立即前往',
        'goToChangePassword': '前往更改密碼',
        'help': '幫助',
        'highestRole': '最高角色（當前組織角色）',
        'host': '主機',
        'incorrectNewPwdConfirmationMessage': '"新密碼確認" 不正確。',
        'industry': '行業',
        'instanceMemory': '應用實體可用記憶體',
        'insufficientPermissionsToReviveMessage': '您沒有足夠的許可權來恢復這位使用者。',
        'invalidUsernameMessage': '"使用者名稱" 格式無效。',
        'invalidNewPwdMessage': '"新密碼" 不符合密碼原則。',
        'invite': '邀請',
        'inviteSuccessfully': '邀請成功。',
        'inviteUserMessage': '使用者已存在。您想邀請此使用者加入您的組織嗎？',
        'lang': '語言',
        'large': '大',
        'lastModifiedTime': '上次修改時間',
        'lastName': '姓氏',
        'lastName*': '姓氏*',
        'ldap': 'LDAP',
        'ldapConnectSuccessfully': '成功連接到 LDAP 伺服器。',
        'ldapDisconnectSuccessfully': '成功斷開與 LDAP 伺服器的連接。',
        'ldapSettings': 'LDAP 設定',
        'ldapTestPassed': '測試通過',
        'ldapUsername': 'LDAP 使用者名稱',
        'ldapUsername*': 'LDAP 使用者名稱*',
        'listProcessingUsersTitle': '列出所有處理中的使用者',
        'loadingOrgs...': '正在載入組織...',
        'loadingSpaces...': '正在載入空間...',
        'manage': '管理',
        'manageFailedUsersTitle': '管理所有失敗的使用者',
        'manageMarketplacesTitle': '管理所有市集',
        'manageMarketplaceTitle': '管理市集',
        'managementPortalIntro': '組織、使用者與服務管理',
        'managementPortalTitle': '管理入口網站',
        'manageReviewersTitle': '管理所有審核人員',
        'manageSrpsHint': '請選擇要列出的組織。',
        'manageSrpsTitle': '管理所有 SRP',
        'manageSrpTitle': '管理 SRP',
        'manageTrainingUsersTitle': '管理培訓用的使用者',
        'manageUsersHint': '請選擇要列出的組織或角色。',
        'manageUsersTitle': '管理所有使用者',
        'manageUserTitle': '管理使用者',
        'mappingToGuidOfSrp': '對應到 Cloud Foundry 上 SRP（App）的 GUID',
        'mappingToOrg': '對應到 Cloud Foundry 的 Org',
        'mappingToSpace': '對應到 Cloud Foundry 的 Space',
        'marketplaceId': '市集 ID',
        'marketplaceId*': '市集 ID*',
        'marketplaceNameIsAlreadyInUse': '市集名稱已被使用。',
        'marketplaces': '市集',
        'marketplace': '市集',
        'medium': '中',
        'moreInfo': '更多資訊',
        'mpFailMessage': '提供的令牌無效。',
        'myProfileTitle': '我的個人資料',
        'mySrps': '我的 SRP',
        'name': '名稱',
        'name*': '名稱*',
        'namingPolicyHint': '允許的符號：底線（_）和破折號（-）。',
        'newOrgHint': '新組織將與使用者一起創建。',
        'newOrgName': '新組織名稱',
        'newPassword': '新密碼',
        'newPassword*': '新密碼*',
        'newPasswordConfirmation*': '新密碼確認*',
        'newPasswordConfirmationHint': '請再次輸入新密碼。',
        'noFailedUser': '沒有失敗的使用者。',
        'noExamplePhone': '無範例電話',
        'noProcessingUser': '沒有處理中的使用者。',
        'noReviewer': '沒有審核人員。',
        'noReviewingUser': '沒有審核中的使用者。',
        'noScopeCanBeAppended': '使用者已擁有這個 SRP 的所有權限。',
        'noScopeCanBeRemoved': '使用者並未擁有這個 SRP 的任何權限。',
        'noSpaceMessage': '沒有任何空間存在，請選擇其他組織。',
        'noSrpMessage': '沒有任何 SRP 存在，請選擇其他空間。',
        'notificationUrl': '通知 URL',
        'notificationUrl*': '通知 URL*',
        'numOfDevelopers': 'Developers 數量',
        'numOfTenants': 'Tenants 數量',
        'officePhone': '辦公室電話',
        'operations': '操作',
        'org': '組織',
        'org*': '組織*',
        'orgId*': '組織 ID*',
        'orgNameAlreadyExists': '組織名稱已存在。',
        'orgNamingPolicyHint': '僅允許的符號：破折號（-）。',
        'origin': '來源',
        'oneRoleOneOrgMessage': '使用者在一個組織中只能被指派為一個角色。',
        'paasPermissionsSetting': 'PaaS 權限設定',
        'paasPermissionSettingList*': 'PaaS 權限設定清單*',
        'pageIsRedirecting...': '頁面正在重新導向...',
        'partOfMarketplaceName': '部份的市集名稱',
        'partOfSrpName': '部份的 SRP 名稱',
        'partOfUsername': '部份的使用者名稱',
        'password': '密碼',
        'password*': '密碼*',
        'passwordExpiresMessage': '您已經有很長一段時間沒有更改密碼了，我們建議您立即更改您的密碼。',
        'passwordExpiresForcedMessage': '您已經有很長一段時間沒有更改密碼了，請立即更改您的密碼。',
        'passwordOperationTitle': '密碼操作',
        'passwordPolicy': '密碼原則',
        'phoneIsInvalid': '該地區的號碼無效。',
        'port': '連接埠',
        'postalCode': '郵遞區號',
        'processingStatus': '處理狀態',
        'processingUsers': '處理中的使用者',
        'reasonForFailure': '失敗原因',
        'redirectingMessage': '頁面將在5秒後重新導向。',
        'refreshingMessage': '頁面將在5秒後重新整理。',
        'regionCode': '地區代碼',
        'regionCodeIsInvalid': '請選擇地區代碼。',
        'rememberMe': '記住我',
        'remindMeNextTime': '下次提醒我',
        'remove': '移除',
        'removeReviewerMessage': '是否確定要將使用者 \'$username\' 從審核人員清單移除？',
        'removeSuccessfully': '移除成功。',
        'resendRegEmail': '重新發送註冊電子郵件',
        'resendRegEmailContent1': '如果您在完成註冊後沒有收到註冊電子郵件，您可以使用此工具重新發送。提交後，您將收到一封包含連結的電子郵件，表示已完成重發程序。',
        'resendRegEmailContent2': '要重新發送註冊電子郵件，請輸入您的使用者名稱（電子郵件），然後按一下 "送出"。',
        'resendRegEmailSuccessfully': '成功重新發送註冊電子郵件。',
        'resendRegEmailTitle': '輸入電子郵件以重新發送註冊電子郵件',
        'reset': '重置',
        'resetPassword': '重置密碼',
        'resetPasswordContent': '您必須使用啟用碼更改密碼並符合密碼原則。密碼原則為:',
        'resetPasswordSuccessfully': '密碼重置成功。',
        'resetSuccessfully': '重置成功。',
        'resetTrainingUsersMessage': '是否確定要重置這些培訓用的使用者？',
        'returnToLogin': '返回登入',
        'reviewers': '審核人員',
        'reviewingUsers': '審核中的使用者',
        'revive': '恢復',
        'reviveCheckingMessage': '請選擇1位使用者',
        'reviveFailedUserTitle': '恢復失敗的使用者',
        'reviveSuccessfully': '恢復成功。',
        'role': '角色',
        'role*': '角色*',
        'ownedScopes': '擁有的權限',
        'save': '儲存',
        'scopes': '權限',
        'scopes*': '權限*',
        'selectNumberOfTenantsOrDevelopersMessage': '請選擇 tenant 或 developer 的數量。',
        'sendPwdResetEmail': '發送密碼重置電子郵件',
        'sendPwdResetEmailContent1': '如果您不記得您的密碼，您可以使用此工具重置它。提交後，您將收到一封包含連結的電子郵件，表示已完成重置程序。',
        'sendPwdResetEmailContent2': '要發送密碼重置電子郵件，請輸入您的使用者名稱（電子郵件），然後按一下 "送出"。',
        'sendPwdResetEmailSuccessfully': '成功發送密碼重置電子郵件。',
        'sendPwdResetEmailTitle': '輸入電子郵件以發送密碼重置電子郵件',
        'show': '顯示',
        'signIn': '登入',
        'signInAgain': ' 請重新登入。',
        'signInFirst': ' 請先登入。',
        'signingInWithThirdParty...': '正在使用第三方登入...',
        'signInTitle': '登入 Developer Network',
        'signInWithThird-party': '使用第三方登入',
        'signOut': '登出',
        'signUp': '註冊',
        'signUpSuccessfully': '註冊成功。我們將審核您的帳戶。在審核通過後，您將收到一封註冊電子郵件。',
        'signUpTitle': '註冊',
        'skip': '略過',
        'small': '小',
        'space': '空間',
        'space*': '空間*',
        'spaceId*': '空間 ID*',
        'spaces': '空間',
        'spaces*': '空間*',
        'splitingPolicyHint': '使用逗號分隔權限，例如：讀取，寫入等。',
        'srp': 'SRP',
        'srp*': 'SRP*',
        'srpNameIsAlreadyInUse': '指定的組織和空間中該 SRP 名稱已被使用。',
        'srpId': 'SRP ID',
        'srpId*': 'SRP ID*',
        'srps': 'SRPs',
        'standard': '標準',
        'status': '狀態',
        'submit': '送出',
        'supportPortalIntro': '線上支援與討論',
        'supportPortalTitle': '支援入口網站',
        'sure': '確定',
        'systemNotification': '系統通知',
        'technicalPortalIntro': '平台相關技術文件',
        'technicalPortalTitle': '技術入口網站',
        'tel': '電話',
        'tenantOnlyMessage': '此頁面操作取決於您在組織中的權限。',
        'test': '測試',
        'thePasswordPolicy:': '密碼原則：',
        'ticketerOnlyMessage': '工單人員不能與其他角色同時存在。',
        'totalMemory': '可用記憶體總量',
        'totalRoute': '可用路由總數',
        'totalService': '可用服務總數',
        'trainingUserList': '培訓用的使用者清單',
        'trainingUsers': '培訓用的使用者',
        'trainingUsersTitle': '培訓用的使用者',
        'uid': '唯一識別碼（uid）',
        'unlimited': '無限制',
        'unlock': '解鎖',
        'unlockYourAccount': '解鎖您的帳戶',
        'unlockYourAccountContent': '您必須在首次登入時更改預設密碼並符合密碼原則。密碼原則是：',
        'unlockSuccessfully': '解鎖成功。請重新登入。',
        'updateSuccessfully': '更新成功。',
        'useOrgsLink': '使用現有的組織',
        'userId': '使用者 ID',
        'userIsAlreadyAReviewer': '使用者已經是審核人員。',
        'username': '使用者名稱（電子郵件）',
        'username*': '使用者名稱（電子郵件）*',
        'usernameIsAlreadyInUse': '使用者名稱已被使用。',
        'user': '使用者',
        'userAlreadyExistsInOrg': '使用者已經存在於您的組織中, 請使用 "管理使用者" 功能更新。',
        'users': '使用者',
        'validPeriod*': '有效期間（天）*',
        'youDoNotHaveAnyOrg': '您沒有任何 org。',
        'youDoNotHaveAnySrp': '您沒有任何 SRP。'
    },
    'zh-CN': {
        '*requiredFields': '* 必要字段',
        '1.assignARole': '1. 指派角色',
        '1.selectAnOrg': '1. 选择组织',
        '2.assignAnOrg': '2. 指派组织（星号（*）代表所有组织）',
        '2.selectASpace': '2. 选择空间',
        '3.assignSpaces': '3. 指派空间（星号（*）代表指派组织的所有空间）',
        '3.selectASrp': '3. 选择 SRP',
        '4.selectScopes': '4. 选择权限',
        'accessIsDenied': '存取被拒。',
        'accounts': '帐户',
        'action*': '操作*',
        'activate': '启用',
        'activateCheckingMessage': '请勾选1或多位用户。',
        'activateQuotaCheckingMessage': '如果要使用配额计划启用审核中的用户，请确认仅勾选1位用户。',
        'activateReviewingUsersTitle': '启用所有审核中的用户',
        'activateReviewingUserWithPlanTitle': '依计划启用审核中的用户',
        'activateSuccessfully': '启用成功。',
        'activationCode': '启用码',
        'activationCode*': '启用码*',
        'add': '添加',
        'address': '地址',
        'addSuccessfully': '添加成功。',
        'adminOnlyMessage': '管理员不能与其他角色同时存在。',
        'advancedUserProfile': '进阶用戶资料',
        'all': '全部',
        'alternativeEmail': '备用电子邮件',
        'append': '追加',
        'appId*': 'App ID*',
        'appInstanceLimit': '应用实体总数上限',
        'assignQuota': '指派额度',
        'assignRoleAndOrgMessage': '请至少指派一个角色和一个组织给用户。',
        'assignSpaceMessage': '请至少指派一个空间给用户。',
        'assignSpaceToDeveloperMessage': '当 developer 的数量不等于零时, 请至少指派一个空间。',
        'atLeast1Digit': '至少1个数字',
        'atLeast1LowerCaseLetter': '至少1个小写字母',
        'atLeast1SpecialCharacter': '至少1个特殊字符',
        'atLeast1UpperCaseLetter': '至少1个大写字母',
        'atLeast8Characters': '至少8个字符',
        'attention': '注意',
        'authenticationTest': '认证测试',
        'baseDns': '基础可分辨名称',
        'baseDnsSplitingPolicyHint': '使用分号分隔基础可分辨名称，例如：ou=x,dc=com;ou=y,dc=com。',
        'baseUsername*': '基础用戶名称*',
        'basicUserProfile': '基本用戶资料',
        'bindDn': '绑定可分辨名称',
        'cancel': '取消',
        'cfScopes': 'CF 权限',
        'change': '更改',
        'changePasswordSuccessfully': '密码更改成功。请重新登入。',
        'changePasswordTitle': '更改密码',
        'chooseAPlanForCurrentUser*': '为当前用户选择一个计划*',
        'city': '城市',
        'clear': '清除',
        'close': '关闭',
        'completeRegistrationTitle': '完整注册',
        'company': '公司',
        'company*': '公司*',
        'contactPhone': '联络电话',
        'continue': '继续',
        'country': '国家 / 地区',
        'create': '创建',
        'createMarketplaceTitle': '创建新的市集',
        'createOrgLink': '创建新的组织',
        'createSrpTitle': '创建新的SRP',
        'createSuccessfully': '创建成功。',
        'createTrainingUsersTitle': '创建培训用的用户',
        'createUserTitle': '创建用户',
        'creationTime': '创建时间',
        'creator': '创建者',
        'currentUser': '当前用户',
        'configLdapContent': '<strong>如何测试：</strong><p>请输入 LDAP 用户的用户名称和密码, 然后单击 "测试" 按钮。</p>',
        'confirm': '确认',
        'connect': '连接',
        'data-error': '请输入正确的格式。',
        'data-error-email': '请输入正确的电子邮件格式。',
        'data-error-url': '请输入正确的 URL 格式。',
        'data-match-error': '输入两次的新密码不一致。',
        'data-minlength-error': '长度不足。',
        'data-pattern-error': '请符合所需格式。',
        'data-pattern-error-basic': '请符合所需格式。（不能使用大于（>）和小于（<））',
        'data-required-error': '请填写这个字段。',
        'deactivate': '取消启用',
        'deactivateSuccessfully': '取消启用成功。',
        'delete': '删除',
        'deleteMarketplaceMessage': '是否确定要删除市集？',
        'deleteSrpMessage': '是否确定要删除 SRP？',
        'deleteSuccessfully': '删除成功。',
        'deleteTrainingUsersMessage': '是否确定要删除这些培训用的用户？',
        'description': '描述',
        'didn\'tReceiveTheRegistrationEmail?': '没有收到注册电子邮件？',
        'disable': '停用',
        'disableSuccessfully': '停用成功。',
        'disableUserMessage': '是否确定要停用用户？',
        'disconnect': '断开连接',
        'don\'tHaveAccount?': '没有帐户？',
        'e.g.': '例如：',
        'edit': '编辑',
        'editUserScopesTitle': '编辑用户权限',
        'emptyActivationCodeMessage': '"授权代码" 字段不能为空。',
        'emptyNewPwdConfirmationMessage': '"新密码确认" 字段不能为空。',
        'emptyNewPwdMessage': '"新密码" 字段不能为空。',
        'emptyPwdMessage': '"密码" 字段不能为空。',
        'emptyResult': '没有结果。',
        'emptyUsernameMessage': '"用户名称" 字段不能为空。',
        'enable': '启用',
        'enabled': '启用',
        'enableSuccessfully': '启用成功。',
        'enableUserMessage': '是否确定要启用用户？',
        'enterManually': '手动输入',
        'exceptSpaceBackslashAndDoubleQuotes': '禁止空格（ ）、反斜杠（\\）、双引号（"）字符',
        'failedUsers': '失败的用户',
        'fieldName': '域名',
        'fieldValue': '域值',
        'firstName': '名字',
        'firstName*': '名字*',
        'firstTimeSignedInMessage': '您为首次登入，我们建议您立即更改默认密码。',
        'firstTimeSignedInForcedMessage': '您为首次登入，请立即更改默认密码。',
        'forgetPassword?': '忘记密码？',
        'fuzzySearch': '模糊搜寻',
        'generateAutomatically': '自动产生',
        'go': '立即前往',
        'goToChangePassword': '前往更改密码',
        'help': '帮助',
        'highestRole': '最高角色（当前组织角色）',
        'host': '主机',
        'incorrectNewPwdConfirmationMessage': '"新密码确认" 不正确。',
        'industry': '行业',
        'instanceMemory': '应用实体可用内存',
        'insufficientPermissionsToReviveMessage': '您没有足够的权限来恢复这位用户。',
        'invalidUsernameMessage': '"用户名称" 格式无效。',
        'invalidNewPwdMessage': '"新密码" 不符合密码原则。',
        'invite': '邀请',
        'inviteSuccessfully': '邀请成功。',
        'inviteUserMessage': '用户已存在。您想邀请此用户加入您的组织吗？',
        'lang': '语言',
        'large': '大',
        'lastModifiedTime': '上次修改时间',
        'lastName': '姓氏',
        'lastName*': '姓氏*',
        'ldap': 'LDAP',
        'ldapConnectSuccessfully': '成功连接到 LDAP 服务器。',
        'ldapDisconnectSuccessfully': '成功断开与 LDAP 服务器的连接。',
        'ldapSettings': 'LDAP 设定',
        'ldapTestPassed': '测试通过',
        'ldapUsername': 'LDAP 用户名称',
        'ldapUsername*': 'LDAP 用户名称*',
        'listProcessingUsersTitle': '列出所有处理中的用户',
        'loadingOrgs...': '正在加载组织...',
        'loadingSpaces...': '正在加载空间...',
        'manage': '管理',
        'manageFailedUsersTitle': '管理所有失败的用户',
        'manageMarketplacesTitle': '管理所有市集',
        'manageMarketplaceTitle': '管理市集',
        'managementPortalIntro': '组织、用户与服务管理',
        'managementPortalTitle': '管理门户',
        'manageReviewersTitle': '管理所有审核人员',
        'manageSrpsHint': '请选择要列出的组织。',
        'manageSrpsTitle': '管理所有 SRP',
        'manageSrpTitle': '管理 SRP',
        'manageTrainingUsersTitle': '管理培训用的用户',
        'manageUsersHint': '请选择要列出的组织或角色。',
        'manageUsersTitle': '管理所有用户',
        'manageUserTitle': '管理用户',
        'mappingToGuidOfSrp': '对应到 Cloud Foundry 上 SRP（App）的 GUID',
        'mappingToOrg': '对应到 Cloud Foundry 的 Org',
        'mappingToSpace': '对应到 Cloud Foundry 的 Space',
        'marketplaceId': '市集 ID',
        'marketplaceId*': '市集 ID*',
        'marketplaceNameIsAlreadyInUse': '市集名称已被使用。',
        'marketplaces': '市集',
        'marketplace': '市集',
        'medium': '中',
        'moreInfo': '更多信息',
        'mpFailMessage': '提供的令牌无效。',
        'myProfileTitle': '我的个人资料',
        'mySrps': '我的 SRP',
        'name': '名称',
        'name*': '名称*',
        'namingPolicyHint': '允许的符号：底线（_）和破折号（-）。',
        'newOrgHint': '新组织将与用户一起创建。',
        'newOrgName': '新组织名称',
        'newPassword': '新密码',
        'newPassword*': '新密码*',
        'newPasswordConfirmation*': '新密码确认*',
        'newPasswordConfirmationHint': '请再次输入新密码。',
        'noFailedUser': '没有失败的用户。',
        'noExamplePhone': '无范例电话',
        'noProcessingUser': '没有处理中的用户。',
        'noReviewer': '没有审核人员。',
        'noReviewingUser': '没有审核中的用户。',
        'noScopeCanBeAppended': '用户已拥有这个 SRP 的所有权限。',
        'noScopeCanBeRemoved': '用户并未拥有这个 SRP 的任何权限。',
        'noSpaceMessage': '没有任何空间存在，请选择其他组织。',
        'noSrpMessage': '没有任何 SRP 存在，请选择其他空间。',
        'notificationUrl': '通知 URL',
        'notificationUrl*': '通知 URL*',
        'numOfDevelopers': 'Developers 数量',
        'numOfTenants': 'Tenants 数量',
        'officePhone': '办公室电话',
        'operations': '操作',
        'org': '组织',
        'org*': '组织*',
        'orgId*': '组织 ID*',
        'orgNameAlreadyExists': '组织名称已存在。',
        'orgNamingPolicyHint': '仅允许的符号：破折号（-）。',
        'origin': '来源',
        'oneRoleOneOrgMessage': '用户在一个组织中只能被指派为一个角色。',
        'paasPermissionsSetting': 'PaaS 权限设定',
        'paasPermissionSettingList*': 'PaaS 权限设定列表*',
        'pageIsRedirecting...': '页面正在重新导向...',
        'partOfMarketplaceName': '部份的市集名称',
        'partOfSrpName': '部份的 SRP 名称',
        'partOfUsername': '部份的用户名称',
        'password': '密码',
        'password*': '密码*',
        'passwordExpiresMessage': '您已经有很长一段时间没有更改密码了，我们建议您立即更改您的密码。',
        'passwordExpiresForcedMessage': '您已经有很长一段时间没有更改密码了，请立即更改您的密码。',
        'passwordOperationTitle': '密码操作',
        'passwordPolicy': '密码原则',
        'phoneIsInvalid': '该地区的号码无效。',
        'port': '端口',
        'postalCode': '邮政编码',
        'processingStatus': '处理状态',
        'processingUsers': '处理中的用户',
        'reasonForFailure': '失败原因',
        'redirectingMessage': '页面将在5秒后重新导向。',
        'refreshingMessage': '页面将在5秒后重新整理。',
        'regionCode': '地区代码',
        'regionCodeIsInvalid': '请选择地区代码。',
        'rememberMe': '记住我',
        'remindMeNextTime': '下次提醒我',
        'remove': '移除',
        'removeReviewerMessage': '是否确定要将用户 \'$username\' 从审核人员列表移除？',
        'removeSuccessfully': '移除成功。',
        'resendRegEmail': '重新发送注册电子邮件',
        'resendRegEmailContent1': '如果您在完成注册后没有收到注册电子邮件，您可以使用此工具重新发送。提交后，您将收到一封包含链接的电子邮件，表示已完成重发程序。',
        'resendRegEmailContent2': '要重新发送注册电子邮件，请输入您的用户名称（电子邮件），然后单击 "送出"。',
        'resendRegEmailSuccessfully': '成功重新发送注册电子邮件。',
        'resendRegEmailTitle': '输入电子邮件以重新发送注册电子邮件',
        'reset': '重置',
        'resetPassword': '重置密码',
        'resetPasswordContent': '您必须使用启用码更改密码并符合密码原则。密码原则为:',
        'resetPasswordSuccessfully': '密码重置成功。',
        'resetSuccessfully': '重置成功。',
        'resetTrainingUsersMessage': '是否确定要重置这些培训用的用户？',
        'returnToLogin': '返回登入',
        'reviewers': '审核人员',
        'reviewingUsers': '审核中的用户',
        'revive': '恢复',
        'reviveCheckingMessage': '请选择1位用户',
        'reviveFailedUserTitle': '恢复失败的用户',
        'reviveSuccessfully': '恢复成功。',
        'role': '角色',
        'role*': '角色*',
        'ownedScopes': '拥有的权限',
        'save': '储存',
        'scopes': '权限',
        'scopes*': '权限*',
        'selectNumberOfTenantsOrDevelopersMessage': '请选择 tenant 或 developer 的数量。',
        'sendPwdResetEmail': '发送密码重置电子邮件',
        'sendPwdResetEmailContent1': '如果您不记得您的密码，您可以使用此工具重置它。提交后，您将收到一封包含链接的电子邮件，表示已完成重置程序。',
        'sendPwdResetEmailContent2': '要发送密码重置电子邮件，请输入您的用户名称（电子邮件），然后单击 "送出"。',
        'sendPwdResetEmailSuccessfully': '成功发送密码重置电子邮件。',
        'sendPwdResetEmailTitle': '输入电子邮件以发送密码重置电子邮件',
        'show': '显示',
        'signIn': '登入',
        'signInAgain': ' 请重新登入。',
        'signInFirst': ' 请先登入。',
        'signingInWithThirdParty...': '正在使用第三方登入...',
        'signInTitle': '登入 Developer Network',
        'signInWithThird-party': '使用第三方登入',
        'signOut': '注销',
        'signUp': '注册',
        'signUpSuccessfully': '注册成功。我们将审核您的帐户。在审核通过后，您将收到一封注册电子邮件。',
        'signUpTitle': '注册',
        'skip': '略过',
        'small': '小',
        'space': '空间',
        'space*': '空间*',
        'spaceId*': '空间 ID*',
        'spaces': '空间',
        'spaces*': '空间*',
        'splitingPolicyHint': '使用逗号分隔权限，例如：读取，写入等。',
        'srp': 'SRP',
        'srp*': 'SRP*',
        'srpNameIsAlreadyInUse': '指定的组织和空间中该 SRP 名称已被使用。',
        'srpId': 'SRP ID',
        'srpId*': 'SRP ID*',
        'srps': 'SRPs',
        'standard': '标准',
        'status': '状态',
        'submit': '送出',
        'supportPortalIntro': '在线支持与讨论',
        'supportPortalTitle': '支持门户',
        'sure': '确定',
        'systemNotification': '系统通知',
        'technicalPortalIntro': '平台相关技术文件',
        'technicalPortalTitle': '技术门户',
        'tel': '电话',
        'tenantOnlyMessage': '此页面操作取决于您在组织中的权限。',
        'test': '测试',
        'thePasswordPolicy:': '密码原则：',
        'ticketerOnlyMessage': '工单人员不能与其他角色同时存在。',
        'totalMemory': '可用内存总量',
        'totalRoute': '可用路由总数',
        'totalService': '可用服务总数',
        'trainingUserList': '培训用的用户列表',
        'trainingUsers': '培训用的用户',
        'trainingUsersTitle': '培训用的用户',
        'uid': '唯一标识符（uid）',
        'unlimited': '无限制',
        'unlock': '解锁',
        'unlockYourAccount': '解锁您的帐户',
        'unlockYourAccountContent': '您必须在首次登入时更改默认密码并符合密码原则。密码原则是：',
        'unlockSuccessfully': '解锁成功。请重新登入。',
        'updateSuccessfully': '更新成功。',
        'useOrgsLink': '使用现有的组织',
        'userId': '用户 ID',
        'userIsAlreadyAReviewer': '用户已经是审核人员。',
        'username': '用户名称（电子邮件）',
        'username*': '用户名称（电子邮件）*',
        'usernameIsAlreadyInUse': '用户名称已被使用。',
        'user': '用户',
        'userAlreadyExistsInOrg': '用户已经存在于您的组织中, 请使用 "管理用户" 功能更新。',
        'users': '用户',
        'validPeriod*': '有效期间（天）*',
        'youDoNotHaveAnyOrg': '您没有任何 org。',
        'youDoNotHaveAnySrp': '您没有任何 SRP。'
    }
};